### ISSUE TITLE
yolov5的库版本

### ISSUE THREAD

**Issue by Zoe-My** [shuyansy/A-detection-and-recognition-pipeline-of-complex-meters-in-wild#22]
我想知道best.pt和textgraph_vgg_100.pth两个模型是通过哪个库版本的yolov5训练得到的，是v6.0吗，因为我想将他部署在TensorRT上加速，因此需要对应的库版本，谢谢

**Comment by kangyiyun** [comment]
请问您是在哪里找到best.pt这个文件的呢？可以分享一下么

**Comment by Zoe-My** [comment]
> 请问您是在哪里找到best.pt这个文件的呢？可以分享一下么

https://drive.google.com/file/d/1bHYpJro3ERmNTRO2JEo1inyU0_juqw5z/view

**Comment by YimengQian** [comment]
1. 请问您是在哪里找到textgraph_vgg_100.pth这个文件的呢？请问可以分享一下吗 谢谢

**Comment by Zoe-My** [comment]
> 1. 请问您是在哪里找到textgraph_vgg_100.pth这个文件的呢？请问可以分享一下吗 谢谢

https://drive.google.com/file/d/1sHmEEf9E0_kvL0LW1S5Y5jjFgjx_O5Dj/view

**Comment by YimengQian** [comment]
谢谢谢谢>C<
