### ISSUE TITLE
Failure example

### ISSUE THREAD

**Issue by zhouzq-thu** [shuyansy/A-detection-and-recognition-pipeline-of-complex-meters-in-wild#8]
![Screen Shot 2023-07-17 at 18 09 19](https://github.com/shuyansy/Detect-and-read-meters/assets/9458157/ccc714bc-bc3f-4b67-b707-cd5804a00ac8)

**Comment by shuyansy** [comment]
I m sorry about that and i admit that our data is relatively scarce and limited to some kinds of meters. Maybe you can finetune the trained model with some of your data with annotations. Hope it can help you!
